# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x07term_id\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\"\'\n\tterm_vote\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0c\n\x04vote\x18\x02 \x01(\x08\"&\n\nid_address\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"\x18\n\x06period\x12\x0e\n\x06period\x18\x01 \x01(\x05\"\'\n\x0bterm_leader\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t2\xa3\x01\n\x04raft\x12#\n\x0bRequestVote\x12\x08.term_id\x1a\n.term_vote\x12\'\n\rAppendEntries\x12\x08.term_id\x1a\x0c.term_leader\x12\x30\n\tGetLeader\x12\x16.google.protobuf.Empty\x1a\x0b.id_address\x12\x1b\n\x07Suspend\x12\x07.period\x1a\x07.periodb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TERM_ID._serialized_start=43
  _TERM_ID._serialized_end=78
  _TERM_VOTE._serialized_start=80
  _TERM_VOTE._serialized_end=119
  _ID_ADDRESS._serialized_start=121
  _ID_ADDRESS._serialized_end=159
  _PERIOD._serialized_start=161
  _PERIOD._serialized_end=185
  _TERM_LEADER._serialized_start=187
  _TERM_LEADER._serialized_end=226
  _RAFT._serialized_start=229
  _RAFT._serialized_end=392
# @@protoc_insertion_point(module_scope)
