# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x13\n\x04inpt\x12\x0b\n\x03inp\x18\x01 \x01(\t\"&\n\rreverse_input\x12\x15\n\rreverse_input\x18\x01 \x01(\t\"\x14\n\x04text\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x05parts\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05parts\x18\x02 \x03(\t\"\x12\n\x03num\x12\x0b\n\x03num\x18\x01 \x03(\x05\"\x12\n\x03\x61ns\x12\x0b\n\x03\x61ns\x18\x01 \x03(\t2Z\n\x07service\x12 \n\x07reverse\x12\x05.inpt\x1a\x0e.reverse_input\x12\x16\n\x05split\x12\x05.text\x1a\x06.parts\x12\x15\n\x07isprime\x12\x04.num\x1a\x04.ansb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPT._serialized_start=17
  _INPT._serialized_end=36
  _REVERSE_INPUT._serialized_start=38
  _REVERSE_INPUT._serialized_end=76
  _TEXT._serialized_start=78
  _TEXT._serialized_end=98
  _PARTS._serialized_start=100
  _PARTS._serialized_end=138
  _NUM._serialized_start=140
  _NUM._serialized_end=158
  _ANS._serialized_start=160
  _ANS._serialized_end=178
  _SERVICE._serialized_start=180
  _SERVICE._serialized_end=270
# @@protoc_insertion_point(module_scope)
