# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reverse = channel.unary_unary(
                '/service/reverse',
                request_serializer=service__pb2.inpt.SerializeToString,
                response_deserializer=service__pb2.reverse_input.FromString,
                )
        self.split = channel.unary_unary(
                '/service/split',
                request_serializer=service__pb2.text.SerializeToString,
                response_deserializer=service__pb2.parts.FromString,
                )
        self.isprime = channel.unary_unary(
                '/service/isprime',
                request_serializer=service__pb2.num.SerializeToString,
                response_deserializer=service__pb2.ans.FromString,
                )


class serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def split(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isprime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reverse': grpc.unary_unary_rpc_method_handler(
                    servicer.reverse,
                    request_deserializer=service__pb2.inpt.FromString,
                    response_serializer=service__pb2.reverse_input.SerializeToString,
            ),
            'split': grpc.unary_unary_rpc_method_handler(
                    servicer.split,
                    request_deserializer=service__pb2.text.FromString,
                    response_serializer=service__pb2.parts.SerializeToString,
            ),
            'isprime': grpc.unary_unary_rpc_method_handler(
                    servicer.isprime,
                    request_deserializer=service__pb2.num.FromString,
                    response_serializer=service__pb2.ans.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service/reverse',
            service__pb2.inpt.SerializeToString,
            service__pb2.reverse_input.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def split(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service/split',
            service__pb2.text.SerializeToString,
            service__pb2.parts.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def isprime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service/isprime',
            service__pb2.num.SerializeToString,
            service__pb2.ans.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
