# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x07\x61\x64\x64ress\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\"!\n\x08\x61ssigned\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01m\x18\x02 \x01(\t\"\x1b\n\x02id\x12\x15\n\rderegister_id\x18\x01 \x01(\x05\"\'\n\x03msg\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0bpopulate_id\x12\x13\n\x0bpopulate_id\x18\x01 \x01(\x05\"\x18\n\x05pairs\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1d\n\nnodes_list\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\",\n\x0c\x66inger_table\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"%\n\x08key_text\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"+\n\x0bsuccess_msg\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x90\x02\n\x05\x63hord\x12\x1f\n\x08register\x12\x08.address\x1a\t.assigned\x12\x17\n\nderegister\x12\x03.id\x1a\x04.msg\x12\x36\n\x15populate_finger_table\x12\x0c.populate_id\x1a\r.finger_table0\x01\x12\x37\n\x0eget_chord_info\x12\x16.google.protobuf.Empty\x1a\x0b.nodes_list0\x01\x12;\n\x10get_finger_table\x12\x16.google.protobuf.Empty\x1a\r.finger_table0\x01\x12\x1f\n\x04save\x12\t.key_text\x1a\x0c.success_msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESS._serialized_start=44
  _ADDRESS._serialized_end=67
  _ASSIGNED._serialized_start=69
  _ASSIGNED._serialized_end=102
  _ID._serialized_start=104
  _ID._serialized_end=131
  _MSG._serialized_start=133
  _MSG._serialized_end=172
  _POPULATE_ID._serialized_start=174
  _POPULATE_ID._serialized_end=208
  _PAIRS._serialized_start=210
  _PAIRS._serialized_end=234
  _NODES_LIST._serialized_start=236
  _NODES_LIST._serialized_end=265
  _FINGER_TABLE._serialized_start=267
  _FINGER_TABLE._serialized_end=311
  _KEY_TEXT._serialized_start=313
  _KEY_TEXT._serialized_end=350
  _SUCCESS_MSG._serialized_start=352
  _SUCCESS_MSG._serialized_end=395
  _CHORD._serialized_start=398
  _CHORD._serialized_end=670
# @@protoc_insertion_point(module_scope)
